import type { Metadata } from "next";
import "./globals.css";
import MainHeader from "@/components/main-header/main-header";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body className="flex flex-col items-center bg-primary-base text-white">
                <MainHeader />
                <main className="w-full flex flex-col p-5 gap-10">
                    {children}
                </main>
            </body>
        </html>
    );
}
